apiVersion: v1
kind: Pod
metadata:
  name: test-readiness-httpget
  namespace: default
  labels:
    app: myapp
    version: v1
spec:
  containers:
    - name: mynginx
      image: nginx
      imagePullPolicy: IfNotPresent
      readinessProbe:
        httpGet:
          port: 80
          path: /fake_index.html
        initialDelaySeconds: 1
        periodSeconds: 3
