apiVersion: v1
kind: Pod
metadata:
  name: test-liveness-exec
  namespace: default
  labels:
    app: myapp
    version: v1
spec:
  containers:
    - name: mynginx
      image: nginx
      imagePullPolicy: IfNotPresent
      command: ['sh','-c','touch /tmp/test; sleep 20; rm -rf /tmp/test']
      livenessProbe:
        exec:
          command: ['test','-e','/tmp/test']
        initialDelaySeconds: 1
        periodSeconds: 3
