apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: test-conjob
spec:
  schedule: '* * * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: busybox
              command: ['sh','-c','date;echo hello from the k8s cluster']
          restartPolicy: OnFailure
