apiVersion: v1
kind: Pod
metadata:
  name: test-configmap-volume
spec:
  containers:
    - name: cm-container-2
      image: alpine
      command: ["/bin/sh","-c","ping 8.8.8.8"]
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: test-cm-2
  restartPolicy: Never
