apiVersion: v1
kind: Pod
metadata:
  name: test-configmap-cmd
spec:
  containers:
    - name: cm-container-2
      image: alpine
      imagePullPolicy: IfNotPresent
      command: [ "/bin/sh", "-c", "echo please login to ${DATABASE_URI} with username ${name} and password ${password}" ]
      env:
        - name: DATABASE
          valueFrom:
            configMapKeyRef:
              name: test-cm-3
              key: database
        - name: DATABASE_URI
          valueFrom:
            configMapKeyRef:
              name: test-cm-3
              key: database_uri
      envFrom:
        - configMapRef:
            name: test-cm-4
  restartPolicy: Never
