apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mynginx-basicauth
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - xiaofu'
spec:
  rules:
    - host: auth.xiaofu.com
      http:
        paths:
          - path: /
            backend:
              serviceName: mynginx-service
              servicePort: 8080
