apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-nodeselector
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: deployment-app
    spec:
      nodeSelector:
        level: boss
      containers:
        - name: mynginx
          image: mynginx:v2
          ports:
            - containerPort: 80
