apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-nodename
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: deployment-app
    spec:
      nodeName: k8s-node1  
      containers:
        - name: mynginx
          image: mynginx:v2
          ports:
            - containerPort: 80
