apiVersion: v1
kind: Pod
metadata:
  name: test-podaffinity-hard
  labels:
    app: app2
spec:
  containers:
    - name: mynginx
      image: mynginx:v2
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - app1
          topologyKey: kubernetes.io/hostname 
