apiVersion: v1
kind: Pod
metadata:
  name: test-podaffinity-soft
  labels:
    app: app2
spec:
  containers:
    - name: mynginx
      image: mynginx:v2
  affinity:
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - test
            topologyKey: kubernetes.io/hostname
