apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mynginx-https
spec:
  tls:
    - hosts:
      - secret.xiaofu.com
      secretName: tls-secret
  rules:
    - host: secret.xiaofu.com
      http:
        paths:
          - path: /
            backend:
              serviceName: mynginx-service
              servicePort: 8080
